- name: init ansible_flags directory
  shell: mkdir -p /etc/ansible_flags/ || true
  changed_when: false

- name: read ansible_flags
  find:
    paths: /etc/ansible_flags/
  register:
    ansible_flags

#####################

- name: init ansible_files directory
  shell: mkdir -p /etc/ansible_files/ || true
  changed_when: false

- name: upload LXD-related files
  copy:
    src: "files/pkgs/{{ item }}"
    dest: "/etc/ansible_files/{{ item }}"
    mode: 0755
    backup: true
  with_items:
    - ifupdown_0.8.17ubuntu1.1_amd64.deb
    - libpython2.7-minimal_2.7.15~rc1-1_amd64.deb
    - libpython2.7-stdlib_2.7.15~rc1-1_amd64.deb
    - libpython-stdlib_2.7.15~rc1-1_amd64.deb
    - python_2.7.15~rc1-1_amd64.deb
    - python2.7_2.7.15~rc1-1_amd64.deb
    - python2.7-minimal_2.7.15~rc1-1_amd64.deb
    - python-minimal_2.7.15~rc1-1_amd64.deb
  vars:
    ansible_flag_check_filename: "lxd-related-files-8" # increment the number when adds files
  when:
    ((ansible_flags | json_query("files[?path=='/etc/ansible_flags/" + ansible_flag_check_filename + "'].path") | length()) == 0)

# 注: ↑  apt-get -y update && apt-get -y install ifupdown libpython2.7-minimal libpython2.7-stdlib libpython-stdlib python python2.7 python2.7-minimal python-minimal の結果で収集

- name: touch flags for LXD-related files
  shell: |
    touch /etc/ansible_flags/lxd-related-files-8 # increment the number when adds files
  changed_when: false

- name: configure guest loop
  include: make_guest.yml
  loop:
    "{{ lxd_guests }}"
  loop_control:
    loop_var: guest

- name: flush the LXD sqlite database
  shell: |
    lxd sql global .sync || true
    lxd sql local .sync || true
  changed_when:
    false



