- name: init ansible_flags directory
  shell: mkdir -p /etc/ansible_flags/ || true
  changed_when: false

- name: read ansible_flags
  find:
    paths: /etc/ansible_flags/
  register:
    ansible_flags

#####################

- name: install_dotnet_core_3_1_1_arm64
  shell:
    cmd: |
      set -eu
      # Download
      cd /tmp/
      rm -fr /tmp/dotnet3_1_1_arm64/
      mkdir /tmp/dotnet3_1_1_arm64/
      cd /tmp/dotnet3_1_1_arm64/
      wget http://ossvault.open.ad.jp/vault/oss/20012701_dotnet_core_3_1_1/dotnet_sdk/dotnet-sdk-3.1.101-linux-arm64.tar.gz

      # Install
      rm -fr /usr/share/dotnet3_1_1_arm64/
      mkdir -p /usr/share/dotnet3_1_1_arm64/
      tar zxf dotnet-sdk-3.1.101-linux-arm64.tar.gz -C /usr/share/dotnet3_1_1_arm64/
      ln -s -f /usr/share/dotnet3_1_1_arm64/dotnet /usr/bin/dotnet
      # Finalize
      cat <<\EOF >> /root/.bashrc_addtional
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      EOF
      touch "/etc/ansible_flags/{{ ansible_flag_check_filename }}"
    executable: /bin/bash
  vars:
    ansible_flag_check_filename: "install_dotnet_core_3_1_1_arm64"
  when:
    ((ansible_flags | json_query("files[?path=='/etc/ansible_flags/" + ansible_flag_check_filename + "'].path") | length()) == 0)

