- name: try to connect
  raw: /bin/true
  changed_when: false

- name: install python 2
  raw: test -e /usr/bin/python || (export DEBIAN_FRONTEND=noninteractive && apt-get -y update && (apt-get -y install python-minimal || apt-get -y install python2-minimal) && (ln -s python2 /usr/bin/python || true))
  changed_when: false

- name: gathering facts
  setup:
