(setq case-replace nil)
(setq column-number-mode t)
(setq enable-double-n-syntax t)
(setq next-line-add-newlines nil)
(setq scroll-step 1)
(transient-mark-mode t)
(if (eq window-system 'x)
 (progn
  (define-key function-key-map [backspace] [8])
  (put 'backspace 'ascii-character 8)
 )
)
(global-set-key "\C-h" 'backward-delete-char)
(global-set-key [S-right] 'end-of-line)
(global-set-key [S-left]  'beginning-of-line)
(global-set-key "\C-o" 'find-file)
(global-set-key "\C-s" 'save-buffer)
(global-set-key "\C-a" 'write-file)
(global-set-key "\C-e" 'save-buffers-kill-emacs)
(global-set-key "\C-z" 'undo)
(global-set-key "\C-r" 'replace-string)
(global-set-key "\C-p" 'replace-regexp)
(global-set-key "\C-f" 'isearch-forward)
(global-set-key "\C-i" 'isearch-backward)
(global-set-key "\C-n" 'insert-file)
(global-set-key "\C-b" 'kill-region)
(global-set-key "\C-v" 'yank)
(global-set-key "\C-d" 'copy-region-as-kill)
(global-set-key "\C-c" 'copy-region-as-kill)
(global-set-key "\C-w" 'list-buffers)
(global-set-key "\C-q" 'switch-to-buffer)
