- name: touch /etc/ansible_flags/first_install_rebooted
  shell: |
    touch /etc/ansible_flags/first_install_rebooted
  changed_when: false

- name: reboot - reboot the host
  shell:
    cmd: |
      nohup bash -c "sync; sleep 3; /sbin/reboot --force; /sbin/reboot" &
    executable: /bin/bash
  ignore_errors: true

- name: reboot - wait for host down
  wait_for:
    host: "{{ common_ssh_host }}"
    port: "{{ common_ssh_port }}"
    timeout: 300
    connect_timeout: 1
    delay: 1
    state: stopped
  delegate_to: localhost
  become: false
  when: (not (no_reboot | default()))

- name: reboot - wait for host up
  wait_for:
    host: "{{ common_ssh_host }}"
    port: "{{ common_ssh_port }}"
    timeout: 500
    connect_timeout: 1
    delay: 1
    search_regex: SSH
    state: started
  delegate_to: localhost
  become: false
  when: (not (no_reboot | default()))

