- name: init ansible_flags directory
  shell: mkdir -p /etc/ansible_flags/ || true
  changed_when: false

- name: read ansible_flags
  find:
    paths: /etc/ansible_flags/
  register:
    ansible_flags

#####################

- name: install_dotnet_core_5_0_rtm
  shell:
    cmd: |
      set -eu
      bash -x <(curl -4 --insecure --pinnedpubkey "sha256//lvnOVgA0u06WySztudkn+urQda/zFBRd65A5wCmcBpQ=" --raw --silent https://static.lts.dn.ipantt.net/d/210111_002_microsoft_dotnet_sdk_12255/210209_ubuntu_install_dotnet_5.0.103.sh)
      touch "/etc/ansible_flags/{{ ansible_flag_check_filename }}"
    executable: /bin/bash
  vars:
    ansible_flag_check_filename: "install_dotnet_core_5_0_rtm"
  when:
    ((ansible_flags | json_query("files[?path=='/etc/ansible_flags/" + ansible_flag_check_filename + "'].path") | length()) == 0)

